# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d404771e8fec4b6cb766dee7bee90571d6a23271731aa7f3aa5ea50e67128817856ca3c263035ce792f578be1d4619b82664de853cc404caad704c499a7eabb

test:
  secret_key_base: 2b6a968536b7445f2307d17b833e0045d8ca9082eeb8a3c59941bb4d51bfd250a3174b0f309602ab9ff9994493587ef2ecd18b08aa1e9e107f067133320593f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
